spring.application.name=bffcn2

server.port=8080

azure.functions.usuarios=https://functioncn2-fdayc5gwhcazf8en.eastus2-01.azurewebsites.net/api/usuarios
azure.functions.prestamos=https://functioncn2-fdayc5gwhcazf8en.eastus2-01.azurewebsites.net/api/prestamos

azure.functions.graphql.usuarios=https://functioncn2-fdayc5gwhcazf8en.eastus2-01.azurewebsites.net/api/graphql/usuarios
azure.functions.graphql.prestamos=https://functioncn2-fdayc5gwhcazf8en.eastus2-01.azurewebsites.net/api/graphql/prestamos

